### ISSUE TITLE
Bug: accents splits are not shown in dataset JSON summary after release 7

### ISSUE THREAD

**Issue by KathyReid** [common-voice/cv-dataset#12]
Description of bug: 

Since the inception of the Accent functionality, dataset release summary JSON files have contained a summary of the accent splits, see for example: 

https://github.com/common-voice/cv-dataset/blob/main/datasets/cv-corpus-7.0-2021-07-21.json

```
"date": "2021-07-21",
  "locales": {
    "en": {
      "buckets": {
        "dev": 16284,
        "invalidated": 220015,
        "other": 220176,
        "reported": 2732,
        "test": 16284,
        "train": 759975,
        "validated": 1425784
      },
      "reportedSentences": 2679,
      "duration": 9493711987,
      "clips": 1865975,
      "splits": {
        "accent": {
          "": 0.51,
          "canada": 0.03,
          "england": 0.08,
          "us": 0.23,
          "indian": 0.07,
          "australia": 0.03,
          "malaysia": 0,
          "newzealand": 0.01,
          "african": 0.01,
          "ireland": 0.01,
          "philippines": 0,
          "singapore": 0,
          "scotland": 0.02,
          "hongkong": 0,
          "bermuda": 0,
          "southatlandtic": 0,
          "wales": 0,
          "other": 0.01
        },

```

By contrast, v8 and v9 of the release do not contain accent splits: 

```
 "locales": {
        "en": {
            "duration": 10390463635,
            "buckets": {
                "dev": 16326,
                "invalidated": 239065,
                "other": 251332,
                "reported": 3558,
                "test": 16326,
                "train": 864448,
                "validated": 1530385
            },
            "reportedSentences": 3500,
            "clips": 2020782,
            "splits": {
                "accent": {
                    "": 1
                },
                "age": {
                    "": 0.37,
                    "twenties": 0.24,
                    "sixties": 0.04,
                    "thirties": 0.13,
                    "teens": 0.06,
                    "seventies": 0.01,
                    "fourties": 0.1,
                    "fifties": 0.04,
                    "eighties": 0,
                    "nineties": 0
                },
                "gender": {
                    "": 0.37,
                    "male": 0.46,
                    "female": 0.16,
                    "other": 0.02
                }
            },
            "users": 79398,
            "size": 75356163484,
            "checksum": "8b82525e6adb8382e28eabfed1beeedd3f315c1d3cdf7445a3ff33743f42025d",
            "avgDurationSecs": 5.142,
            "validDurationSecs": 7868938.703,
            "totalHrs": 2886.23,
            "validHrs": 2185.81
        },
```

This may be due to the self-identified accent functionality that was implemented some months ago, meaning there are many self-entered accents and no agreed method of grouping them, however accent split data will be very useful for equity, diversity and inclusion measures. 

Kind regards, 
Kathy

**Comment by mozgzh** [comment]
Thanks for leaving feedback. You're correct in that accent data is now free-form, users can also have many accents. As a result, splitting by singular accent values is complex and likely wouldn't represent the data accurately. However, we are still exporting the accent values and as a result, individual calculations can be conducted.

**Comment by KathyReid** [comment]
Thanks so much @mozgzh. When you say you are exporting the accent values, do you mean that they are exported in `validated.tsv`? If so I can use `pandas` to do some summaries.

**Comment by mozgzh** [comment]
Correct, accents are exported in the `.tsv` files per clip, the metadata is delineated by `,` e.g. `British, American` if a clip's contributor had two accents. Hope that helps! I'll close this thread, but please do create new issues for other questions. Thanks again.
