### ISSUE TITLE
Wrong duration value in ar v10.0

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/cv-dataset#17]
Here:
https://github.com/common-voice/cv-dataset/blob/392d53b0b2070deb56cac4b55e7f01384002ecd5/datasets/cv-corpus-10.0-2022-07-04.json#L581

I measured around 523,476,000 (not exact value as calculated back from rounded hours).

**Comment by mozgzh** [comment]
Fixed with #18 ! Thanks for the issue :rocket:

**Comment by HarikalarKutusu** [comment]
Hey @mozgzh, thanks for fixing this. But I think it again has a conversion error, as duration field is measured as milli seconds, not seconds.

**Comment by mozgzh** [comment]
Ah, yes! Added the appropriate ms now :rocket:
