### ISSUE TITLE
need label about sample clean or noisy

### ISSUE THREAD

**Issue by JohnHerry** [common-voice/cv-dataset#23]
As the title, I did not find a tag about whether the speech is clean.  Some of the records are noisy, It maybe usefull for ASR, SV, but not for TTS

**Comment by KathyReid** [comment]
The Common Voice dataset is not intended for TTS.

**Comment by HarikalarKutusu** [comment]
Hey @KathyReid, although CV is for STT, a clean flag would help during training when using augmentation. Current recordings can be categorized as very clean, medium clean/noisy, or noisy. One might augment clean ones heavily, noisy ones can be left as they are, and medium ones can be augmented at a medium level.

Currently, with my augmentations, I just set a medium level and work for it.

It might also help with more scientific research, where we can train with one set and test with another (custom splits) to measure the effect.

On the other hand, that would not be practically applicable with ~20M recordings already at hand which should be tagged.

**Comment by HarikalarKutusu** [comment]
On second thought: **This would be a very very bad idea!**

We all signed up and allowed our voices to be recorded for STT, where our voices become a small bump in the floating point numbers in the model weights.

**NOT for our voices to be replicated!**

Using CV data for TTS should violate our rights, as there are few-shots models now. I think this should be openly stated by Mozilla.
