### ISSUE TITLE
Error: Version 15 summary data does not contain nested objects for splits (age, gender) and buckets (validation)

### ISSUE THREAD

**Issue by KathyReid** [common-voice/cv-dataset#25]
### Description of error

In the newly-released v15 JSON file, the `splits` object and `buckets` object is missing for each `locale` object. This contains data on age, gender and validation splits for each `locale`. This data is required for me to produce the data visualisation of the metadata coverage for Common Voice. The [v15 metadata coverage](https://observablehq.com/@kathyreid/mozilla-common-voice-v15-dataset-metadata-coverage) is done, but it shows errors where the `splits` objects are missing. 

### Outcome sought

Could the JSON file please be re-generated with the `splits` object and `buckets` object for each `locale`? 

### Example of error

Example of locale data for `en` language in [v15 JSON](https://github.com/common-voice/cv-dataset/blob/main/datasets/cv-corpus-15.0-delta-2023-09-08.json): 

```
"en": {
      "duration": 244618020,
      "reportedSentences": 140,
      "clips": 40553,
      "users": 750,
      "size": 1371012179,
      "checksum": "794f4ea6c6bab3731d54cf7ce3d67996cf1ba7c0d92cbd338c36636a9716047a",
      "avgDurationSecs": 5.2,
      "validDurationSecs": 171002.31,
      "totalHrs": 67.95,
      "validHrs": 47.5
    }
```

The same locale data for `en` in [v14 JSON](https://github.com/common-voice/cv-dataset/blob/main/datasets/cv-corpus-14.0-2023-06-23.json): 

```
 "en": {
      "buckets": {
        "dev": 16380,
        "invalidated": 272017,
        "other": 279585,
        "reported": 6445,
        "test": 16380,
        "train": 1046685,
        "validated": 1724421
      },
      "duration": 11802687079,
      "reportedSentences": 6368,
      "clips": 2276023,
      "splits": {
        "accent": {
          "": 1
        },
        "age": {
          "": 0.37,
          "twenties": 0.24,
          "sixties": 0.04,
          "thirties": 0.14,
          "teens": 0.06,
          "seventies": 0.01,
          "fourties": 0.09,
          "fifties": 0.05,
          "eighties": 0,
          "nineties": 0
        },
        "gender": {
          "": 0.37,
          "male": 0.45,
          "female": 0.16,
          "other": 0.02
        }
      },
      "users": 88154,
      "size": 83555475656,
      "checksum": "6e88c7460090c5a6ca7f02a8525bd669e7bc509a47b2f1974977d5065a054507",
      "avgDurationSecs": 5.186,
      "validDurationSecs": 8942265.283,
      "totalHrs": 3278.52,
      "validHrs": 2483.96
    },
```

**Comment by moz-dfeller** [comment]
Hi @KathyReid! It seems that you were checking the delta release, can it be? The stats for the full release are [here](https://github.com/common-voice/cv-dataset/blob/main/datasets/cv-corpus-15.0-2023-09-08.json) :)

**Comment by KathyReid** [comment]
Oh I am an idiot! Thank you @moz-dfeller and apologies for the wasted time looking at this. 
Confirming the [Metadata visualisation for v15](https://observablehq.com/@kathyreid/mozilla-common-voice-v15-dataset-metadata-coverage) is working correctly.

**Comment by moz-dfeller** [comment]
No worries. Glad it's working. Love the visualizations!
