### ISSUE TITLE
FEATURE REQUEST: Please add `duration` as a metadata item that is included in the `*.tsv` files with a release

### ISSUE THREAD

**Issue by KathyReid** [common-voice/cv-dataset#28]
## User story 

As a researcher, I want to be able to run analysis on the duration of clips in Common Voice for various languages and purposes, for example to use Common Voice as an evaluation corpus for speech recognition engines. 

Currently, the clip `duration` is available as an _aggregate_ statistic in the JSON file provided by this (`cv-dataset`) repository. However, it is not available as a metadata data item in, e.g. the `validated.tsv` file. 

As a researcher, this means I must use additional processing to calculate the duration of each `.mp3` clip, which is frustrating if this information is known in advance. 

## Acceptance criteria 

* `duration` in seconds is included for each data item in each `*.tsv` of each dataset

**Comment by moz-dfeller** [comment]
Hey @KathyReid , I believe this can be closed then. As @HarikalarKutusu said, a file that contains clip durations in ms is part of the dataset release already :)
