### ISSUE TITLE
CV v20.0 bad rm-* language codes

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/cv-dataset#36]
There are `rm-surs` and `rm-vall` "locales" with null / zero / -1 values, because they do not exist.

They should be `rm-sursilv` and `rm-vallader`.
Checked again from API and Pontoon in case codes are changed, but no...

**Comment by KathyReid** [comment]
Agree with @HarikalarKutusu's diagnosis here, thank you Bözden!

**Comment by HarikalarKutusu** [comment]
Also, when fixed, probably the CHANGELOG.md values should also change.

https://github.com/common-voice/cv-dataset/blob/6528e8bfa052cb357e855c19f9c21197fbc46ef3/CHANGELOG.md?plain=1#L11

131 + 4 should be 135 (currently 133)

I checked the new v19.0 and v20.0 languages (cumbersome without ISO codes), and they are all there.

**Comment by KathyReid** [comment]
I have a list of all the ISO-639-* and BCP-47 codes used by each language here: 
https://observablehq.com/@kathyreid/mozilla-common-voice-v19-dataset-metadata-coverage#localeMap

**Comment by HarikalarKutusu** [comment]
I get & cache the info from the API, but it has language codes attached to native language names, sometimes hard to decipher. I use Glottolog data and match them automatically to get other related info such as English names, script, language families, countries, etc. I currently get >90% match, non-standard ones like rm-*, zh-* fail thou - actually most of them should be variants, but created like that before we had variants, not conforming to ISO/bcp-47.

I need to create mappings between these problematic ones (not available yet).
Nowadays I collect English/Turkish etc. names from CV repo language files (*.ftl).

@KathyReid, this release has very interesting results, we have huge amount of efforts from multiple locales. Check the totals/delta and delta pages from beta site (missing rm-*):
https://cv-metadata-viewer.netlify.app/
