### ISSUE TITLE
.tsv files not found

### ISSUE THREAD

**Issue by zuther77** [common-voice/cv-dataset#4]
Hi, I downloaded the dataset from the Mozilla common voice website. I downloaded the common voice corpus 1 for the English language. The zip file only contained a single file called 'en' with no extensions that Windows could recognize. 

Is there a way to extract all the .tsv files?

**Comment by phirework** [comment]
Hi, I think this is a problem with your extraction script. I suggest using tar on the command line and just doing something like `tar -xvgf en.tar.gz` - there's definitely TSV files in all of the zips.
